package com.zsdev.gzh.webservice;


import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "WeixinApiService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.biyehome.cn/Ajax/WeixinApiService.asmx?wsdl")
public class WeixinApiService
        extends Service {

    private final static URL WEIXINAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException WEIXINAPISERVICE_EXCEPTION;
    private final static QName WEIXINAPISERVICE_QNAME = new QName("http://tempuri.org/", "WeixinApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.biyehome.cn/Ajax/WeixinApiService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEIXINAPISERVICE_WSDL_LOCATION = url;
        WEIXINAPISERVICE_EXCEPTION = e;
    }

    public WeixinApiService() {
        super(__getWsdlLocation(), WEIXINAPISERVICE_QNAME);
    }

    public WeixinApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEIXINAPISERVICE_QNAME, features);
    }

    public WeixinApiService(URL wsdlLocation) {
        super(wsdlLocation, WEIXINAPISERVICE_QNAME);
    }

    public WeixinApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEIXINAPISERVICE_QNAME, features);
    }

    public WeixinApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeixinApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns WeixinApiServiceSoap
     */
    @WebEndpoint(name = "WeixinApiServiceSoap")
    public WeixinApiServiceSoap getWeixinApiServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WeixinApiServiceSoap"), WeixinApiServiceSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns WeixinApiServiceSoap
     */
    @WebEndpoint(name = "WeixinApiServiceSoap")
    public WeixinApiServiceSoap getWeixinApiServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WeixinApiServiceSoap"), WeixinApiServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEIXINAPISERVICE_EXCEPTION != null) {
            throw WEIXINAPISERVICE_EXCEPTION;
        }
        return WEIXINAPISERVICE_WSDL_LOCATION;
    }

}
