package com.zsdev.gzh.webservice;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "WeixinApiServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WeixinApiServiceSoap {


    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public String helloWorld();

    /**
     * @param orderNumber
     * @param thesisType
     * @param appKey
     * @param spam
     * @param token
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "QueryPaperReport", action = "http://tempuri.org/QueryPaperReport")
    @WebResult(name = "QueryPaperReportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryPaperReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryPaperReport")
    @ResponseWrapper(localName = "QueryPaperReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryPaperReportResponse")
    public String queryPaperReport(
            @WebParam(name = "app_key", targetNamespace = "http://tempuri.org/")
                    String appKey,
            @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
                    String token,
            @WebParam(name = "spam", targetNamespace = "http://tempuri.org/")
                    String spam,
            @WebParam(name = "order_number", targetNamespace = "http://tempuri.org/")
                    String orderNumber,
            @WebParam(name = "thesisType", targetNamespace = "http://tempuri.org/")
                    String thesisType);

    /**
     * @param orderNumber
     * @param thesisType
     * @param appKey
     * @param spam
     * @param token
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "DeleteWeixinPaperInfo", action = "http://tempuri.org/DeleteWeixinPaperInfo")
    @WebResult(name = "DeleteWeixinPaperInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteWeixinPaperInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteWeixinPaperInfo")
    @ResponseWrapper(localName = "DeleteWeixinPaperInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteWeixinPaperInfoResponse")
    public String deleteWeixinPaperInfo(
            @WebParam(name = "app_key", targetNamespace = "http://tempuri.org/")
                    String appKey,
            @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
                    String token,
            @WebParam(name = "spam", targetNamespace = "http://tempuri.org/")
                    String spam,
            @WebParam(name = "order_number", targetNamespace = "http://tempuri.org/")
                    String orderNumber,
            @WebParam(name = "thesisType", targetNamespace = "http://tempuri.org/")
                    String thesisType);

}
